name: Build StreamAwesome

on:
 workflow_dispatch:
 pull_request:
  types: [opened, synchronize, reopened]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Clone Font Awesome Overwrites ✌️
        uses: actions/checkout@v2
        with:
          repository: sebinside/StreamAwesome-Overwrites
          path: StreamAwesome/fonts
          token: ${{ secrets.TOKEN }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and Build 🔧
        working-directory: StreamAwesome
        run: |
          npm install
          npm run build
